export type Botanical = {
  id: string; name: string; latin: string; desc: string; part: string; actives: string; std: string; supports: string;
  cats: string[]; color: string; level: number;
  /** Footage or still shown on the card when it is in focus. Files live in public/media/<file>.(mp4|jpg). */
  clip?: { kind: 'video' | 'image'; file: string };
};

export const CATS: Record<string, string> = { wellness: 'Nutraceutical', food: 'Food & beverage', personal: 'Personal care', animal: 'Animal health', herbal: 'Popular herbal' };
export const CAT_DESC: Record<string, string> = {
  all: 'Fifteen of our standardized extracts, shown in their true colours. Filter by where they go to work.',
  herbal: 'Popular herbal extracts from India and the ancient world, from ashwagandha and curcumin to fenugreek and black mustard.',
  wellness: 'Nutraceuticals and dietary supplements. Botanicals from Ayurvedic, Chinese and European tradition, standardized to the marker the research measured.',
  food: 'Food, functional beverages and RTDs. Extracts that bring antioxidant and functional value to drinks, powders and fortified foods.',
  personal: 'Personal care and cosmetics. Plant antioxidants that take the place of synthetic ingredients in skin and hair formulas.',
  animal: 'Animal health. Plant-based ingredients for livestock, poultry and companion-animal formulas.',
};
export const BOTANICALS: Botanical[] = [
  { id:'greentea', clip:{ kind:'video', file:'greentea' }, name:'Green Tea Extract', latin:'Camellia sinensis', desc:'One of the most studied botanicals in the world, rich in catechins and especially EGCG.', part:'Leaves', actives:'Catechins, EGCG', std:'EGCG ≥ 45 %, total catechins 80 % (HPLC)', supports:'Healthy metabolism, antioxidant protection for cells', cats:['wellness','food','personal'], color:'#B8A46A', level:.58 },
  { id:'ginkgo', clip:{ kind:'image', file:'ginkgo' }, name:'Ginkgo Biloba Extract', latin:'Ginkgo biloba', desc:'From one of the oldest tree species on Earth, used for centuries in traditional wellness.', part:'Leaves', actives:'Flavone glycosides, terpene lactones', std:'24 % flavone glycosides, 6 % terpene lactones (HPLC)', supports:'Healthy circulation, cognitive function', cats:['wellness'], color:'#B8923E', level:.52 },
  { id:'grapeseed', clip:{ kind:'video', file:'grapeseed' }, name:'Grape Seed Extract', latin:'Vitis vinifera', desc:'Packed with proanthocyanidins, a family of potent plant antioxidants that pair well with others.', part:'Seeds', actives:'Proanthocyanidins (OPCs)', std:'Proanthocyanidins ≥ 95 %', supports:'Cardiovascular wellness, healthy circulation', cats:['wellness','food','personal'], color:'#8A3E2E', level:.6 },
  { id:'goji', clip:{ kind:'image', file:'goji' }, name:'Goji Berry Extract', latin:'Lycium barbarum', desc:'A staple of traditional Chinese herbal practice for more than two thousand years.', part:'Berries', actives:'Zeaxanthin, polysaccharides, vitamin C', std:'Polysaccharides 40 %', supports:'Eye health, immune function, vitality', cats:['wellness','food'], color:'#C4532A', level:.5 },
  { id:'turmeric', clip:{ kind:'video', file:'turmeric' }, name:'Turmeric Extract · Curcumin', latin:'Curcuma longa', desc:'The golden spice of Ayurveda, used in India for more than 4,500 years and still one of the best-selling botanicals every year.', part:'Rhizome', actives:'Curcumin and curcuminoids', std:'Curcuminoids 95 % (HPLC)', supports:'Healthy inflammatory response, joint comfort', cats:['wellness','food','personal','animal','herbal'], color:'#E39B12', level:.64 },
  { id:'marigold', clip:{ kind:'video', file:'marigold' }, name:'Marigold Extract', latin:'Tagetes erecta', desc:'Bright African marigold flowers, the main natural source of lutein for eye-health and colour formulas.', part:'Flowers', actives:'Lutein, zeaxanthin', std:'Lutein 80 % (HPLC), zeaxanthin profiled', supports:'Eye health, healthy skin, natural colour', cats:['wellness','food','personal','animal'], color:'#E07A1F', level:.56 },
  { id:'milkthistle', clip:{ kind:'image', file:'milkthistle' }, name:'Milk Thistle Extract', latin:'Silybum marianum', desc:'A flavonoid complex studied extensively for liver health.', part:'Seeds', actives:'Silymarin, silybins', std:'Silymarin 80 %, silybins ≥ 30 % (HPLC)', supports:'Liver health, natural detoxification', cats:['wellness','animal'], color:'#C9AE6B', level:.56 },
  { id:'reishi', clip:{ kind:'image', file:'reishi' }, name:'Reishi Mushroom Extract', latin:'Ganoderma lucidum', desc:'The “mushroom of immortality” of East Asian tradition, valued for its beta-glucans and triterpenes.', part:'Fruiting body', actives:'Beta-glucans, triterpenes', std:'Polysaccharides 30 %, triterpenes profiled', supports:'Immune balance, restful sleep, calm under daily stress', cats:['wellness','food'], color:'#7A3F2A', level:.54 },
  { id:'quercetin', clip:{ kind:'video', file:'quercetin' }, name:'Quercetin with Bromelain', latin:'Sophora japonica · Ananas comosus', desc:'A plant flavonoid and a pineapple enzyme, a classic pairing that works better as a team.', part:'Flower buds · pineapple stem', actives:'Quercetin, bromelain', std:'Quercetin 95 % (HPLC) · bromelain 2,400 GDU/g', supports:'Seasonal wellness, antioxidant protection', cats:['wellness'], color:'#E0BE3C', level:.48 },
  { id:'ashwa', clip:{ kind:'image', file:'ashwa' }, name:'Ashwagandha Extract', latin:'Withania somnifera', desc:'Indian ginseng, native to India and North Africa and grown across the drier regions of Madhya Pradesh, Rajasthan and Kerala.', part:'Root', actives:'Withanolides', std:'Withanolides 5 % (HPLC)', supports:'Stress resilience, energy and vitality', cats:['wellness','food','herbal'], color:'#B39A72', level:.56 },
  { id:'fenugreek', clip:{ kind:'image', file:'fenugreek' }, name:'Fenugreek Seed Extract', latin:'Trigonella foenum-graecum', desc:'A favoured medicinal herb in Greece as early as 4,000 BC, and a staple of Indian curries and chutneys.', part:'Seeds', actives:'Saponins, galactomannan fibre', std:'Saponins 50 %', supports:'Metabolic wellness, sports nutrition', cats:['wellness','food','herbal'], color:'#C8A86A', level:.6 },
  { id:'boswellia', clip:{ kind:'image', file:'boswellia' }, name:'Boswellia Extract', latin:'Boswellia serrata', desc:'Indian frankincense, the resin of the Boswellia tree, used in traditional practice for centuries.', part:'Gum resin', actives:'Boswellic acids, AKBA', std:'Boswellic acids 65 %, AKBA profiled (HPLC)', supports:'Joint comfort, healthy inflammatory response', cats:['wellness','animal','herbal'], color:'#D8C7A0', level:.58 },
  { id:'amla', clip:{ kind:'video', file:'amla' }, name:'Amla Extract', latin:'Phyllanthus emblica', desc:'Indian gooseberry, an Ayurvedic superfood for hair and skin, rich in vitamins, minerals and phytonutrients.', part:'Fruit', actives:'Vitamin C, tannins, polyphenols', std:'Tannins 40 %', supports:'Hair and skin care, healthy circulation', cats:['wellness','food','personal','herbal'], color:'#A57C4E', level:.54 },
  { id:'pomegranate', clip:{ kind:'video', file:'pomegranate' }, name:'Pomegranate Extract', latin:'Punica granatum', desc:'Revered for thousands of years across Greek, Hebrew, Buddhist, Islamic and Christian writings.', part:'Fruit peel', actives:'Ellagic acid, punicalagins', std:'Ellagic acid 40 % (HPLC)', supports:'Antioxidant protection', cats:['wellness','food','personal','herbal'], color:'#93453A', level:.5 },
  { id:'mustard', clip:{ kind:'video', file:'mustard' }, name:'Black Mustard Extract', latin:'Brassica nigra', desc:'The most pungent of the mustards, used traditionally in warming preparations applied to the skin.', part:'Seeds', actives:'Sinigrin', std:'Sinigrin profiled (HPLC)', supports:'Warming topical formulas', cats:['personal','food','herbal'], color:'#5E3A24', level:.52 },
];
